server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:order;
    username: sa
    password: asdqwe123
    #driver-class-name: org.mariadb.jdbc.Driver
    #url: jdbc:mariadb://localhost:3306/schema_name
    #username: root
    #password: asdqwe123

  jpa:
    open-in-view: false
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: embedded
      schema-locations: classpath*:/sql/schema.sql
      data-locations: classpath*:/sql/data.sql